In [1]:
import os

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import itertools
from functools import reduce

from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

from sklearn import utils, preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler

from sklearn import model_selection
from sklearn.model_selection import train_test_split, RandomizedSearchCV

from sklearn.linear_model import RidgeClassifier, Ridge
from sklearn.multioutput import MultiOutputClassifier, MultiOutputRegressor

from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.ensemble import AdaBoostRegressor, AdaBoostClassifier

from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.svm import SVC, SVR

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.naive_bayes import GaussianNB

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
#from skmultilearn.adapt import MLkNN
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.linear_model import RidgeClassifier
#from sklearn.linear_model import RidgeRegressor
from sklearn.ensemble import GradientBoostingRegressor
# Compare Algorithms

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
import statsmodels.api as sm

print(os.listdir("../input"))

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' #Hide messy TensorFlow warnings
#warnings.filterwarnings("ignore") #Hide messy Numpy warnings
#warnings.filterwarnings('ignore', category=DeprecationWarning)


seed = 21

['SGH.csv', 'PPv3.csv']


In [27]:
def getAccuracy(prediction, actual):
    matched = []
    for (p,a) in zip(prediction, actual):
        matched.append(len(set(p.astype(int)) & set(a)))
    return matched

def getPercent(prediction, actual, n):
    matched = []
    for (p,a) in zip(prediction, actual):
        matched.append(set(p.astype(int)) & set(a))
    return sum(len(num) > n for num in matched)/len(matched)*100.00

def getCounts(prediction, actual):
    matched = []
    N = [0,0,0,0,0,0,0,0]
    if len(prediction) == 0: return N
    for (a,p) in zip(actual, prediction):
        matched.append(set(p.astype(int)) & set(a))
    if len(matched) == 0:
        return N
    N[0] = sum(len(num) > 0 for num in matched)/len(matched)*100.00
    N[1] = sum(len(num) > 1 for num in matched)/len(matched)*100.00
    N[2] = sum(len(num) > 2 for num in matched)/len(matched)*100.00
    N[3] = sum(len(num) > 3 for num in matched)/len(matched)*100.00
    N[4] = sum(len(num) > 4 for num in matched)/len(matched)*100.00
    N[5] = sum(len(num) > 5 for num in matched)/len(matched)*100.00
    N[6] = sum(len(num) > 6 for num in matched)/len(matched)*100.00
    N[7] = sum(len(num) > 7 for num in matched)/len(matched)*100.00
#    matched.extend(N)
    return N


def getAccuracy1dCount(prediction, actual):
    iMatched = 0
    print(len(prediction))
    for i in range(0,len(prediction)):
        if prediction[i] == actual[i]:
            iMatched = iMatched +1
    return iMatched

def getAccuracy1dPercentCorrect(prediction, actual):
    iMatched = 0
    print(len(prediction))
    for i in range(0,len(prediction)):
        if prediction[i] == actual[i]:
            iMatched = iMatched +1
    return iMatched/len(prediction) * 100.0


def getAccuracyCount(prediction, actual):
    matched = []
    if len(prediction) == 0: return 0
    for (p,a) in zip(prediction, actual):
#        print ( "p: ", p, " a: ", a, (set(p.astype(int)) & set(a)) )
        matched.append((set(p.astype(int)) & set(a)))
    return sum(len(num) > 0 for num in matched)/len(matched)*100.00

def getIntersection(p1, p2):
    return [reduce(np.intersect1d, (p.astype(int), a.astype(int))) for (p,a) in zip(p1, p2)]

def getUnion(p1, p2):
    if len(p1) == 0: return p2
    return [reduce(np.union1d, (p.astype(int), a.astype(int))) for (p,a) in zip(p1, p2)]

def getUnion1dArray(p1,p2):
    return reduce(np.union1d, (p1,p2))

def getIntersection1dArray(prediction, actual):
    iMatched = 0
#     return reduce(np.intersect1d,([prediction,actual]))
#     for idx, i in enumerate(prediction):
#       if prediction[idx] == actual[idx]:
#         iMatched = iMatched + 1
#     return iMatched

# def getAccuracy1dCount(prediction, actual):
#     iMatched = 0
#     for idx in enumerate(prediction):
#       if prediction[idx] == actual[idx]:
#         iMatched = iMatched + 1
#     return iMatched



def unionPrediction(ff):
    predicted = []
    for i, f in enumerate(ff):
#        i_index = name_.index(sInputDir + f + '.csv')        
        i_index = name_.index(f)        
        if i == 0: predicted = list_[i_index][cols].values
        if i > 0:
            predicted = getUnion(predicted,list_[i_index][cols].values)
    return predicted

def getMatches(prediction, actual):
    matched = []
    for (p,a) in zip(prediction, actual):
        print ( len(p), "** p: ", p, " a: ", a, (set(p.astype(int)) & set(a)) )
        matched.append((set(p.astype(int)) & set(a)))
    return matched

def getMatchedCount(prediction, actual):
    return getAccuracyCount(prediction, actual)

def printPredictions ( prediction, actual ):
    for (p,a) in zip(prediction, actual):
        print ( '[',len(set(p.astype(int) )&set(a.astype(int))),'/',len(p),'',set(p.astype(int) ), ' ', set(a.astype(int)), ' ', set(p.astype(int) )&set(a.astype(int)))

def bins_labels(bins, **kwargs):
    bin_w = (max(bins) - min(bins)) / (len(bins) - 1)
    plt.xticks(np.arange(min(bins)+bin_w/2, max(bins), bin_w), bins, **kwargs)
    plt.xlim(bins[0], bins[-1])

def getColums (idx):
    return list(os.path.splitext(basename(name_[idx]))[0][2:])


def showResult(str_alg, prediction, actual ):
    print( str_alg, " Accuracy predict 1 in 7: ", getAccuracy(prediction, actual))

def printResult(predictions, actual):
    df_result=pd.DataFrame({ 'Predicted':list(predictions), 'Actual':list(actual)})
    print(df_result)  
    
def getStdDeviationOfPrediction(ytestPredicted, y_test):
    print("Removing invalid predictions ( < 0 )")
    ind2remove = np.where(ytestPredicted <= 0)[0]
    ytestPredictedFinal = np.delete(ytestPredicted, ind2remove)
    y_testFinal = np.delete(y_test, ind2remove)
    iM = getAccuracy1dCount(y_testFinal, ytestPredictedFinal)
    print(iM)   
    print(np.std(ytestPredictedFinal-y_testFinal))


print('Done')

Done


In [9]:
pp = pd.read_csv('../input/PPv3.csv')
print(pp.tail())

lr = pd.read_csv('../input/SGH.csv')
#print(lr.describe())

#print(lr)

#print(len(lr))
#lr = lr.sort_values(by=['D'])
#lr = lr.drop_duplicates () ;
print(len(lr))
cols = ['D', 'N1','N2','N3','N4','N5','N6','N7']
lr = lr[cols]
#print(lr.head(30))

#https://pandas.pydata.org/pandas-docs/stable/merging.html
df = pd.concat([pp, lr], axis=1, sort=False)
df = df.dropna()
#print(len(df))
#df.head()
df.reset_index().drop(['D'], axis=1)

cols = ['N1','N2','N3','N4','N5','N6','N7']
lr = df[cols]


# cols = ['L','M','S','R','E','A','V' ,'J','U']
# cols = ['L', 'M', 'R', 'J', 'U']
# X = df[cols]

X = df
#Remove T, D and Results
drop_cols = ['T','D','N1','N2','N3','N4','N5','N6','N7','L','M','S','R','E','A','V' ,'J','U','K']
X = X.drop(drop_cols, axis=1)
related_X = X
dataset = related_X

lresult = np.sort(lr.values[:, ::-1])
print(lresult)

col_n = 2  #Column Number interested
print(lresult)
aa = np.delete(lresult, np.s_[col_n:], axis=1)  
aa = np.delete(aa, np.s_[0:col_n-1], axis=1)  
print('Printing')
print(aa)
#Convert 2d array to Dataframe
y = pd.DataFrame(aa, columns=list('N'))
y.head()
y = aa.astype(int).ravel()
print ( y )

model = sm.OLS(y, X).fit()
predictions = model.predict(X) # make the predictions by the model

#print(model.summary())
corr = X.corr()

             T           L  Lg  Lt  Ls  Lb           S  Sg  St  Ss ...  \
1547  20181217  300.014568   7   5   3   3  359.526457   6   3   7 ...   
1548  20181220  302.236280   7   5  12  11   40.189495   4   2   2 ...   
1549  20181224  305.200567   7   5   1   6   98.931481   2   7   4 ...   
1550  20181227  307.425821   7  11  11   7  142.704093   1   4   7 ...   
1551  20181231  310.396111   7  11   6  11  197.112557   4  11   4 ...   

               U  Ug  Ut  Us  Ub           K  Kg  Kt  Ks  Kb  
1547  255.692043   6   4   1  11  274.279218   7   1   7   2  
1548  256.040966   6   4   1   3  274.120357   7   1   7   1  
1549  256.509451   6   4   2  11  273.908541   7   1   7   4  
1550  256.862581   6   4   2   7  273.749679   7   1   7  12  
1551  257.334785   6   4   5   5  273.537864   7   1   7   3  

[5 rows x 51 columns]
1521
[[ 3. 10. 18. ... 29. 36. 42.]
 [ 6.  8. 22. ... 40. 41. 45.]
 [ 5.  8. 15. ... 21. 35. 36.]
 ...
 [ 8. 10. 16. ... 30. 37. 44.]
 [ 7. 13. 21. ... 29

In [23]:
col_n = 1  #Column Number interested
print(lresult)
aa = np.delete(lresult, np.s_[col_n:], axis=1)  
aa = np.delete(aa, np.s_[0:col_n-1], axis=1)  

# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(aa)

# 3. Transform
onehotlabels = enc.transform(aa).toarray()
onehotlabels.shape
#print(onehotlabels)

#Convert 2d array to Dataframe
y = pd.DataFrame(aa, columns=list('N'))
y.head()
y = aa.astype(int).ravel()
print ( y )

model = sm.OLS(y, X).fit()
predictions = model.predict(X) # make the predictions by the model



[[ 3. 10. 18. ... 29. 36. 42.]
 [ 6.  8. 22. ... 40. 41. 45.]
 [ 5.  8. 15. ... 21. 35. 36.]
 ...
 [ 8. 10. 16. ... 30. 37. 44.]
 [ 7. 13. 21. ... 29. 35. 37.]
 [ 5. 17. 24. ... 45. 46. 49.]]
[3 6 5 ... 8 7 5]


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [15]:
df.head(onehotlabels)

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.numeric.Int64Index'> with these indexers [[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]] of <class 'numpy.ndarray'>

In [ ]:
#MultiOutput
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split

#y = lresult
print(y)
#Input dataset, y
scaled_X = preprocessing.scale(dataset)
# create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(scaled_X, y.astype(int), test_size=0.1, shuffle=False)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)


from sklearn import linear_model
# Necessary imports: 
#from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn import metrics

oModelList = [
    MLPClassifier(hidden_layer_sizes=(300000), max_iter=1000, alpha=0.1,
                           activation='relu', solver='lbfgs', early_stopping=True, verbose=False, shuffle=False, random_state=21,tol=0.000001),

#     MLPRegressor(
#         hidden_layer_sizes=(250,125,63,32,16,8,4),  activation='relu', solver='lbfgs', alpha=0.1, batch_size='auto',
#         learning_rate='adaptive', learning_rate_init=0.1, power_t=0.5, max_iter=1000, shuffle=False,
#         random_state=9, tol=0.000001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
#         early_stopping=True, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

    ]

prediction_results = []
i = 0
for m in oModelList:
    # m = MLPRegressor(
    #     hidden_layer_sizes=(10,10),  activation='tanh', solver='lbfgs', alpha=0.001, batch_size='auto',
    #     learning_rate='constant', learning_rate_init=0.1, power_t=0.5, max_iter=1000, shuffle=False,
    #     random_state=9, tol=0.000001, verbose=10, warm_start=False, momentum=0.9, nesterovs_momentum=True,
    #     early_stopping=True, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

    model = m.fit(X_train, y_train) #[list(item) for item in y_train])
    ytrainPredicted = m.predict(X_train).astype(int)

    iM = getAccuracy1dCount(y_train, ytrainPredicted)
    print(iM)   
    print(np.std(ytrainPredicted-y_train))
    getStdDeviationOfPrediction(ytrainPredicted,y_train)

    #ytestPredicted = m.predict(X_test)
    ytestPredicted = m.predict(X_test).astype(int) #, [list(item) for item in y_train])

    print(ytestPredicted)
    print(y_test)
    
    ytestPredicted[ytestPredicted < 0] = 0
    
    iM = getAccuracy1dCount(y_test, ytestPredicted)
    print(iM)   
    print(np.std(ytestPredicted-y_test))
    getStdDeviationOfPrediction(ytestPredicted,y_test)
    
#    training_score = (getAccuracyCount(ytrainPredicted, y_train))
#    testing_score = (getAccuracyCount(ytestPredicted, y_test))
#    total_score = (training_score + testing_score) #- ( training_score - testing_score )

#    i = i + 1
#    print ( i, " Atleast 1 matched: ", total_score, ' Training: ', training_score, '(', len(ytrainPredicted), ') Test: ', testing_score, '(', len(ytestPredicted), ')')
#    print(len(ytestPredicted),ytestPredicted)
#    prediction_results.append(ytestPredicted)



[3 6 5 ... 8 7 5]
(1368, 40) (1368,)
(153, 40) (153,)


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:9: DataConversionWarning: Data with input dtype int64 were all converted to float64 by the scale function.
  if __name__ == '__main__':
