In [1]:
from toto import *
lresult, dataset = loadTotoData()
print(lresult)
print(dataset)

['SGH.csv', 'PPv3.csv']
Done
1521
[[ 3. 10. 18. ... 29. 36. 42.]
 [ 6.  8. 22. ... 40. 41. 45.]
 [ 5.  8. 15. ... 21. 35. 36.]
 ...
 [ 8. 10. 16. ... 30. 37. 44.]
 [ 7. 13. 21. ... 29. 35. 37.]
 [ 5. 17. 24. ... 45. 46. 49.]]
      Lg  Lt  Ls  Lb  Sg  St  Ss  Sb  Mg  Mt ...  Js  Jb  Ug  Ut  Us  Ub  Kg  \
0     -6  -7   5   4   4  -6  12  11  -7   5 ...  -7  12   3  11   3   4   4   
1     -6  -7  -6  12  -6   4  -7   1  -7   5 ...  -7  -7   3  11   3   3   4   
2     -6   3   3  11  -7   5   2   2  -7  11 ...  -6  11   3  11   3   3   4   
3     -6   3   4  -7  -6   3  -7   3  -7  11 ...  -6   1   3  11   3   3   4   
4     -6   3   2   4   4   1  -7  11  -7  11 ...  -6  12   3  11  -7  -6   4   
5     -6   3  11   4   3  11   3   4  -7  11 ...  -6  -7   3  11  -7  -6   4   
6     -6   3  -6  11   2   3   4  11  -7  -6 ...  11   5   3  11  -7  -6   4   
7      5  12   4   4   3   2  -6  -6   7  -6 ...  11   4   3  11   7  -6   4   
8      5  12   1   2   4  -6  12  -6   7  -6 ...  11  

In [17]:
yPredicted = []
for i in range ( 1, 8 ):
    y = loadResult(lresult, i) # interested in column 1 
    # create training and testing vars
    X_train, X_test, y_train, y_test = train_test_split(dataset, y.astype(int), test_size=0.1, shuffle=False)
    print (X_train.shape, y_train.shape)
    print (X_test.shape, y_test.shape)

    clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,
     max_depth=50, min_samples_leaf=2)

    clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                                   max_depth=1000, min_samples_leaf=1)

    classifier = clf_entropy  
    m = classifier.fit(X_train, y_train)  

    ytrainPredicted = m.predict(X_train)
    print ("Training Accuracy is #", i, accuracy_score(y_train,ytrainPredicted)*100)


    # iM = getAccuracy1dCount(y_train, ytrainPredicted) 
    # print(np.std(ytrainPredicted-y_train))
    # getStdDeviationOfPrediction(ytrainPredicted,y_train)

    ytestPredicted = m.predict(X_test)
    print ("Test Accuracy is #", i, accuracy_score(y_test,ytestPredicted)*100)

    #ytestPredicted = m.predict(X_test).astype(int) #, [list(item) for item in y_train])

#    print(ytestPredicted)
#    print(y_test)

    if ( len(yPredicted) == 0 ):
      yPredicted = ytestPredicted
    else:
      yPredicted = np.hstack((yPredicted,yPredicted))

    iM = getAccuracy1dCount(y_test, ytestPredicted)
    print(np.std(ytestPredicted-y_test))
    getStdDeviationOfPrediction(ytestPredicted,y_test)

    
print(yPredicted)



/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and sil

(1368, 40) (1368,)
(153, 40) (153,)
Training Accuracy is # 1 79.53216374269006
Test Accuracy is # 1 15.032679738562091
153
6.565072364133639
Removing invalid predictions ( < 0 )
153
23
6.565072364133639
(1368, 40) (1368,)
(153, 40) (153,)
Training Accuracy is # 2 76.46198830409357
Test Accuracy is # 2 3.9215686274509802
153
9.056946489931065
Removing invalid predictions ( < 0 )
153
6
9.056946489931065
(1368, 40) (1368,)
(153, 40) (153,)
Training Accuracy is # 3 75.51169590643275
Test Accuracy is # 3 3.9215686274509802
153
9.733766420206553
Removing invalid predictions ( < 0 )
153
6
9.733766420206553
(1368, 40) (1368,)
(153, 40) (153,)
Training Accuracy is # 4 74.63450292397661
Test Accuracy is # 4 1.9607843137254901
153
9.55893916471032
Removing invalid predictions ( < 0 )
153
3
9.55893916471032
(1368, 40) (1368,)
(153, 40) (153,)
Training Accuracy is # 5 74.3421052631579
Test Accuracy is # 5 5.228758169934641
153
9.438134807997633
Removing invalid predictions ( < 0 )
153
8
9.438134807

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
